name: CI - Test, Docker Push, and Deploy via SCP

on:
  push:
    branches: [ main ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest

    - name: Copy deploy.sh to target server via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.TARGET_HOST }}
        username: ${{ secrets.TARGET_USER }}
        key: ${{ secrets.TARGET_SSH_KEY }}
        port: 22
        source: "deploy.sh"
        target: "~/my-node-app"

    - name: Execute deploy.sh on remote server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.TARGET_HOST }}
        username: ${{ secrets.TARGET_USER }}
        key: ${{ secrets.TARGET_SSH_KEY }}
        script: |
          chmod +x ~/my-node-app/deploy.sh
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} ~/my-node-app/deploy.sh
