name: CI - Test, Docker Push, Deploy to Target and Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest

    - name: Deploy container to target server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.TARGET_HOST }}
        username: ${{ secrets.TARGET_USER }}
        key: ${{ secrets.TARGET_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest
          docker stop my-node-app || true
          docker rm my-node-app || true
          docker run -d --name my-node-app -p 4444:4444 ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_CONTENT }}
      run: |
        echo "$KUBECONFIG_FILE" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        kubectl apply -f k8s-deployment.yaml
